/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Defines a value for a duplicate fitness event with a count */
@org.apache.avro.specific.AvroGenerated
public class FitnessDuplicateEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8731331578465399833L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FitnessDuplicateEvent\",\"namespace\":\"za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro\",\"doc\":\"Defines a value for a duplicate fitness event with a count\",\"fields\":[{\"name\":\"USERID\",\"type\":[\"null\",\"string\"],\"doc\":\"The simulated user who sent the fitness data\",\"default\":null},{\"name\":\"TENANT_ID\",\"type\":[\"null\",\"int\"],\"doc\":\"The simulated tenant id\",\"default\":null},{\"name\":\"COUNT_DUPLICATES\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FitnessDuplicateEvent> ENCODER =
      new BinaryMessageEncoder<FitnessDuplicateEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FitnessDuplicateEvent> DECODER =
      new BinaryMessageDecoder<FitnessDuplicateEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FitnessDuplicateEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FitnessDuplicateEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FitnessDuplicateEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FitnessDuplicateEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FitnessDuplicateEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FitnessDuplicateEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FitnessDuplicateEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FitnessDuplicateEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The simulated user who sent the fitness data */
   private java.lang.CharSequence USERID;
  /** The simulated tenant id */
   private java.lang.Integer TENANT_ID;
   private java.lang.Long COUNT_DUPLICATES;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FitnessDuplicateEvent() {}

  /**
   * All-args constructor.
   * @param USERID The simulated user who sent the fitness data
   * @param TENANT_ID The simulated tenant id
   * @param COUNT_DUPLICATES The new value for COUNT_DUPLICATES
   */
  public FitnessDuplicateEvent(java.lang.CharSequence USERID, java.lang.Integer TENANT_ID, java.lang.Long COUNT_DUPLICATES) {
    this.USERID = USERID;
    this.TENANT_ID = TENANT_ID;
    this.COUNT_DUPLICATES = COUNT_DUPLICATES;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return USERID;
    case 1: return TENANT_ID;
    case 2: return COUNT_DUPLICATES;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: USERID = (java.lang.CharSequence)value$; break;
    case 1: TENANT_ID = (java.lang.Integer)value$; break;
    case 2: COUNT_DUPLICATES = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'USERID' field.
   * @return The simulated user who sent the fitness data
   */
  public java.lang.CharSequence getUSERID() {
    return USERID;
  }


  /**
   * Sets the value of the 'USERID' field.
   * The simulated user who sent the fitness data
   * @param value the value to set.
   */
  public void setUSERID(java.lang.CharSequence value) {
    this.USERID = value;
  }

  /**
   * Gets the value of the 'TENANT_ID' field.
   * @return The simulated tenant id
   */
  public java.lang.Integer getTENANTID() {
    return TENANT_ID;
  }


  /**
   * Sets the value of the 'TENANT_ID' field.
   * The simulated tenant id
   * @param value the value to set.
   */
  public void setTENANTID(java.lang.Integer value) {
    this.TENANT_ID = value;
  }

  /**
   * Gets the value of the 'COUNT_DUPLICATES' field.
   * @return The value of the 'COUNT_DUPLICATES' field.
   */
  public java.lang.Long getCOUNTDUPLICATES() {
    return COUNT_DUPLICATES;
  }


  /**
   * Sets the value of the 'COUNT_DUPLICATES' field.
   * @param value the value to set.
   */
  public void setCOUNTDUPLICATES(java.lang.Long value) {
    this.COUNT_DUPLICATES = value;
  }

  /**
   * Creates a new FitnessDuplicateEvent RecordBuilder.
   * @return A new FitnessDuplicateEvent RecordBuilder
   */
  public static za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder newBuilder() {
    return new za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder();
  }

  /**
   * Creates a new FitnessDuplicateEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FitnessDuplicateEvent RecordBuilder
   */
  public static za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder newBuilder(za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder other) {
    if (other == null) {
      return new za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder();
    } else {
      return new za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder(other);
    }
  }

  /**
   * Creates a new FitnessDuplicateEvent RecordBuilder by copying an existing FitnessDuplicateEvent instance.
   * @param other The existing instance to copy.
   * @return A new FitnessDuplicateEvent RecordBuilder
   */
  public static za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder newBuilder(za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent other) {
    if (other == null) {
      return new za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder();
    } else {
      return new za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for FitnessDuplicateEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FitnessDuplicateEvent>
    implements org.apache.avro.data.RecordBuilder<FitnessDuplicateEvent> {

    /** The simulated user who sent the fitness data */
    private java.lang.CharSequence USERID;
    /** The simulated tenant id */
    private java.lang.Integer TENANT_ID;
    private java.lang.Long COUNT_DUPLICATES;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.USERID)) {
        this.USERID = data().deepCopy(fields()[0].schema(), other.USERID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.TENANT_ID)) {
        this.TENANT_ID = data().deepCopy(fields()[1].schema(), other.TENANT_ID);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.COUNT_DUPLICATES)) {
        this.COUNT_DUPLICATES = data().deepCopy(fields()[2].schema(), other.COUNT_DUPLICATES);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing FitnessDuplicateEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.USERID)) {
        this.USERID = data().deepCopy(fields()[0].schema(), other.USERID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TENANT_ID)) {
        this.TENANT_ID = data().deepCopy(fields()[1].schema(), other.TENANT_ID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.COUNT_DUPLICATES)) {
        this.COUNT_DUPLICATES = data().deepCopy(fields()[2].schema(), other.COUNT_DUPLICATES);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'USERID' field.
      * The simulated user who sent the fitness data
      * @return The value.
      */
    public java.lang.CharSequence getUSERID() {
      return USERID;
    }


    /**
      * Sets the value of the 'USERID' field.
      * The simulated user who sent the fitness data
      * @param value The value of 'USERID'.
      * @return This builder.
      */
    public za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder setUSERID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.USERID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'USERID' field has been set.
      * The simulated user who sent the fitness data
      * @return True if the 'USERID' field has been set, false otherwise.
      */
    public boolean hasUSERID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'USERID' field.
      * The simulated user who sent the fitness data
      * @return This builder.
      */
    public za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder clearUSERID() {
      USERID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TENANT_ID' field.
      * The simulated tenant id
      * @return The value.
      */
    public java.lang.Integer getTENANTID() {
      return TENANT_ID;
    }


    /**
      * Sets the value of the 'TENANT_ID' field.
      * The simulated tenant id
      * @param value The value of 'TENANT_ID'.
      * @return This builder.
      */
    public za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder setTENANTID(java.lang.Integer value) {
      validate(fields()[1], value);
      this.TENANT_ID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TENANT_ID' field has been set.
      * The simulated tenant id
      * @return True if the 'TENANT_ID' field has been set, false otherwise.
      */
    public boolean hasTENANTID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TENANT_ID' field.
      * The simulated tenant id
      * @return This builder.
      */
    public za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder clearTENANTID() {
      TENANT_ID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'COUNT_DUPLICATES' field.
      * @return The value.
      */
    public java.lang.Long getCOUNTDUPLICATES() {
      return COUNT_DUPLICATES;
    }


    /**
      * Sets the value of the 'COUNT_DUPLICATES' field.
      * @param value The value of 'COUNT_DUPLICATES'.
      * @return This builder.
      */
    public za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder setCOUNTDUPLICATES(java.lang.Long value) {
      validate(fields()[2], value);
      this.COUNT_DUPLICATES = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'COUNT_DUPLICATES' field has been set.
      * @return True if the 'COUNT_DUPLICATES' field has been set, false otherwise.
      */
    public boolean hasCOUNTDUPLICATES() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'COUNT_DUPLICATES' field.
      * @return This builder.
      */
    public za.co.goldmine.kafka.streams.fitness_duplicate_detector.avro.FitnessDuplicateEvent.Builder clearCOUNTDUPLICATES() {
      COUNT_DUPLICATES = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FitnessDuplicateEvent build() {
      try {
        FitnessDuplicateEvent record = new FitnessDuplicateEvent();
        record.USERID = fieldSetFlags()[0] ? this.USERID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.TENANT_ID = fieldSetFlags()[1] ? this.TENANT_ID : (java.lang.Integer) defaultValue(fields()[1]);
        record.COUNT_DUPLICATES = fieldSetFlags()[2] ? this.COUNT_DUPLICATES : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FitnessDuplicateEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<FitnessDuplicateEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FitnessDuplicateEvent>
    READER$ = (org.apache.avro.io.DatumReader<FitnessDuplicateEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.USERID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.USERID);
    }

    if (this.TENANT_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.TENANT_ID);
    }

    if (this.COUNT_DUPLICATES == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.COUNT_DUPLICATES);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.USERID = null;
      } else {
        this.USERID = in.readString(this.USERID instanceof Utf8 ? (Utf8)this.USERID : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.TENANT_ID = null;
      } else {
        this.TENANT_ID = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.COUNT_DUPLICATES = null;
      } else {
        this.COUNT_DUPLICATES = in.readLong();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.USERID = null;
          } else {
            this.USERID = in.readString(this.USERID instanceof Utf8 ? (Utf8)this.USERID : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.TENANT_ID = null;
          } else {
            this.TENANT_ID = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.COUNT_DUPLICATES = null;
          } else {
            this.COUNT_DUPLICATES = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










